### ISSUE TITLE
Displaying panorama(s) on tablet devices

### ISSUE THREAD

**Issue by Pure899** [leopuleo/easy-panorama#4]
First off, thanks for this plugin. Been using it for a while now and very pleased with the functionality on desktop computers.

However, I started noticing more and more, that on tablet devices (like the Samsung Tab and iPad) the panorama more often doesn't load correct (displaying the failure message). Only refreshing the browser a couple of times seem to do the trick.

I've checked the settings and don't see anything not in place. Have you heard more people mentioning this behaviour and is there a possible fix for it?

**Comment by leopuleo** [comment]
Hello @Pure899,
thanks for posting your issue here.

Could you please post at least one link to a page with the problem?
Thank you!

**Comment by leopuleo** [comment]
Hi @Pure899, 
I found a bug in the order the front-end scripts were enqueued. 
#5 fixes it.

I pushed the new version (1.1.1) to WordPress repository, so you will find it in the updates. 
Otherwise, you can download the master branch. 

Please, let me know if it's working. 
Thank you!

**Comment by Pure899** [comment]
Hi @leopuleo 
The panorama's still tend to not show correctly and display the failure message. 
Another URL as an example: https://voetzoekers.nl/het-drentse-landschap/de-palms

**Comment by leopuleo** [comment]
Hello!
Did you update the plugin to version 1.1.1?

As I can see, the website is still using version 1.1.0, or maybe I got a cached version.

Could you please check?
Thank you.

**Comment by Pure899** [comment]
You are correct! I was just able to update it to version 1.1.1 (could have sworn I did so before posting the previous message). Will check it again on multiple devices and post feedback.

**Comment by Pure899** [comment]
Sorry for the delay on the feedback.

On the latest OSX on both iPad and iPhone I haven't noticed any errors. On an older Android device (running 4.4.2) the errors still occur. But since its on a very outdated system that could also be causing the problem (they do still occur on those devices. I have also checked on one newer Android device running the latest Android version and there I did not notice any errors.

If you want more details just let me know and ill see if I can get you those.

Cheers
